import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@/components/analytics";
import { ModeToggle } from "@/components/mode-toggle";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen text-black bg-white dark:text-white dark:bg-[#111010] ${GeistSans.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-2xl mx-auto py-10 px-4">
            <header>
              <div className="flex items-center justify-between">
                <nav className="text-sm font-medium space-x-6">
                  <Link href="/">home</Link>
                  <Link href="/about">about</Link>
                </nav>
                <ModeToggle />
              </div>
            </header>
            <main className="flex flex-1">{children}</main>
            <footer className="flex justify-center gap-12">
              <a>
                <span>email</span>
              </a>
              <a href="https://github.com/freeitas">
                <span>github</span>
              </a>
              <a href="https://www.linkedin.com/in/guilhermehfds/">
                <span>linkedin</span>
              </a>
            </footer>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
